server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: inventory-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/inventory/**
        - id: orders-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/orders/**
        - id: product-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/products/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
