spring:
  application:
    name: ms-products
  jpa:
    ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5431/ms_products
    username: root
    password: toor

server:
  port: 8081
